### ISSUE TITLE
from dataloader import get_data

### ISSUE THREAD

**Issue by cmyyy** [cmudeeplearning11785/Fall2018-tutorials#2]
i tried this on my computer ,but went wrong.where can i download the dataloader?thx!

**Comment by rbrigden** [comment]
Not sure what you are referring to.

**Comment by nikitajz** [comment]
@rbrigden this one:
`from dataloader import get_data`
from [Python for Deep Learning.ipynb](https://github.com/cmudeeplearning11785/Fall2018-tutorials/blob/master/recitation-0/Python%20for%20Deep%20Learning.ipynb)
